---
- name: Run preflight checks
  include_tasks: preflight.yml

- name: Install catalog worker
  become: true
  yum:
    name: "{{ connector_packages }}"

- name: Ensure config directory exists
  become: true
  file:
    path: "{{ catalog_config_dir }}"
    recurse: true
    state: directory

- name: Write Catalog Worker config file
  become: true
  template:
    dest: "{{ catalog_config_dir }}/catalog.toml"
    mode: 0640
    src: catalog.toml.j2

- name: Optionally write RHCD config file
  become: true
  template:
    dest: "{{ rhc_config_dir }}/config.toml"
    mode: 0640
    src: config.toml.j2

- name: Start the rhcd systemd service
  become: true
  systemd:
    unit: rhcd
    enabled: true
    state: started
